### ISSUE TITLE
bLogs?

### ISSUE THREAD

**Issue by Gitsmackt** [WilliamWelsh/ClassicDarkRPAdvert#1]
Basically I use blogs (logging system) and I've replaced the default DarkRP advert, and now I can't see the adverts in my blogs. I was wondering if there was any way you could make a local function for advert so that I can use it in blogs

**Comment by WilliamWelsh** [comment]
Hello, Gitsmackt. Sorry that you encountered this issue. I have updated the addon, please install this and let me know if it works. Unfortunately, I do not have a local server with DarkRP on it at the moment, so I am unable to test it myself.

**Comment by Gitsmackt** [comment]
Thank you however my issue is now fixed. It was regards to something conflicting with the addon.

**Comment by WilliamWelsh** [comment]
Ah, okay. Did you still try the new version? Or are you still using the old version (so I can keep this version the same).

**Comment by Gitsmackt** [comment]
I haven't tried the new version unfortunately.

**Comment by WilliamWelsh** [comment]
Alright, I'm glad you got it to work. I'll go ahead a close this. :)
